spring:
  application:
    name: order-service

  rabbitmq:
    host: rabbitmq-external
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}

  datasource:
    url: jdbc:postgresql://orderdb-postgres-service:5431/orderdb
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8001

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      group:
        liveness:
          include: orderServiceHealth
          show-details: always
        deep:
          include: orderServiceDeepCheck
          show-details: always

payment:
  service:
    url: http://payment-service:8002/api/v1/payments
  healthcheck:
    url: http://payment-service:8002/actuator/health/paymentServiceHealth
  deepcheck:
    url: http://payment-service:8002/actuator/health/paymentServiceDeepCheck

test:
  prefix: "TEST_"