apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentdb-postgres-deployment
  namespace: healthcheck-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: paymentdb-postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "paymentdb"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: paymentdb-postgres-secret
                  key: PAYMENTDB_POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: paymentdb-postgres-secret
                  key: PAYMENTDB_POSTGRES_PASSWORD
          volumeMounts:
            - name: paymentdb-postgres-storage
              mountPath: /var/lib/postgresql # Changed from /var/lib/postgresql/data
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: paymentdb-postgres-storage
          persistentVolumeClaim:
            claimName: paymentdb-postgres-pvc
        - name: init-sql
          configMap:
            name: paymentdb-postgres-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paymentdb-postgres-pvc
  namespace: healthcheck-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: paymentdb-postgres-service
  namespace: healthcheck-demo
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
