spring:
  application:
    name: order-service

  jpa:
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  level:
    org:
      springframework:
        kafka:
          core:
            KafkaTemplate: DEBUG

server:
  port: 8001