spring:
  application:
    name: order-service

  jpa:
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
    listener:
      ack-mode: manual_immediate

server:
  port: 8001

payment:
  service:
    url: "http://localhost:8002/api/v1/payments"

inventory:
  service:
    url: "http://localhost:8003/api/v1/inventory"