services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ server
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  postgres:
    container_name: order-postgres
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=orderdb'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
    ports:
      - '5431:5432'
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql


volumes:
  rabbitmq-data: