spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: order-service
            uri: http://localhost:8001
            predicates:
              - Path=/api/v1/orders/**
            filters:
              - AddRequestHeader=X-From-Gateway, true
          - id: pickup-service
            uri: http://localhost:8002
            predicates:
              - Path=/api/v1/pickups/**
            filters:
              - AddRequestHeader=X-From-Gateway, true
          - id: user-service
            uri: http://localhost:8003
            predicates:
              - Path=/auth/login,/auth/register
server:
  port: 8888