# deployment/name-service-deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: name-service
  namespace: service-discovery
spec:
  replicas: 3
  selector:
    matchLabels:
      app: name-service
  template:
    metadata:
      labels:
        app: name-service
    spec:
      containers:
        - name: name-service
          image: varunu2892/name-service:latest
          ports:
            - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: name-service
  namespace: service-discovery
spec:
  selector:
    app: name-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  type: ClusterIP