# deployment/webapp-deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: service-discovery
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: varunu2892/webapp:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: service-discovery
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer