apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: greeting-service-external-config
data:
  application.properties: |-
    config.greeting=Hello
    config.greetings.en=Hello
    config.greetings.es=Hola
    config.greetings.fr=Bonjour
    config.greetings.cn=Nǐ hǎo
    config.greetings.jp=Kon'nichiwa
    spring.application.name=greeting-service
    server.port=8002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: greeting-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeting-service
  template:
    metadata:
      labels:
        app: greeting-service
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: greeting-service-external-config
            items:
              - key: application.properties
                path: application.properties
      containers:
        - name: greeting-service
          image: varunu2892/greeting-service:latest
          env:
            - name: SPRING_CONFIG_LOCATION
              value: "/etc/config/application.properties"
          ports:
            - containerPort: 8002
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
---
apiVersion: v1
kind: Service
metadata:
  name: greeting-service
spec:
  selector:
    app: greeting-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002