apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: name-service-external-config
data:
  application.properties: |-
    config.name=Varun
    spring.application.name=name-service
    server.port=8001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: name-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: name-service
  template:
    metadata:
      labels:
        app: name-service
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: name-service-external-config
            items:
              - key: application.properties
                path: application.properties
      containers:
        - name: name-service
          image: varunu2892/name-service:latest
          env:
            - name: SPRING_CONFIG_LOCATION
              value: "/etc/config/application.properties"
          ports:
            - containerPort: 8001
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
---
apiVersion: v1
kind: Service
metadata:
  name: name-service
spec:
  selector:
    app: name-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
