spring:
  application:
    name: orderservice

  datasource:
    url: jdbc:postgresql://localhost:5432/order-service
    username: order-user
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8001