# traefik-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: api-gateway
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: traefik
  ports:
    - protocol: TCP
      name: web
      port: 8000
      targetPort: 8000
