# traefik-clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traefik-gateway-controller
rules:
  - apiGroups:
      - "" # Core API group
    resources:
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - traefik.io
      - traefik.containo.us # Older group name, good to include for compatibility
    resources:
      - middlewares
      - middlewaretcps
      - ingressroutes
      - ingressroutetcps
      - ingressrouteudps
      - serverstransports
      - serverstransporttcps
      - tlsoptions
      - tlsstores
      - traefikservices
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - gatewayclasses
      - gateways
      - httproutes
      - tcproutes
      - tlsroutes
      - grpcroutes
      - referencegrants
    verbs:
      - get
      - list
      - watch
  - apiGroups: # Permissions for status updates on Gateway API resources
      - gateway.networking.k8s.io
    resources:
      - gatewayclasses/status
      - gateways/status
      - httproutes/status
      - tcproutes/status
      - tlsroutes/status
      - grpcroutes/status
    verbs:
      - update
      - patch