# traefik-clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traefik-gateway-controller-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-gateway-controller # Name of the ClusterRole defined above
subjects:
  - kind: ServiceAccount
    name: traefik-ingress-controller # Name of your ServiceAccount
    namespace: api-gateway # Namespace of your ServiceAccount