version: '3.8'

services:
  consul:
    image: hashicorp/consul:latest
    container_name: consul-server
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8302:8302"
      - "8500:8500"
      - "8600:8600/udp" # DNS
    command: agent -server -bootstrap -ui -client=0.0.0.0
    networks:
      - consul-network

networks:
  consul-network:
    driver: bridge