spring:
  application:
    name: insurance-service
server:
  port: 8081

logging:
  level:
    com:
      varunu28:
        insuranceservice:
          filter:
            FailureInjectingFilter: DEBUG
