services:
  postgres:
    image: 'postgres:latest'
    container_name: 'inventorydb'
    environment:
      - 'POSTGRES_DB=inventorydb'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5434:5432'
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
