spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://localhost:5432/paymentdb
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8002

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      group:
        deep:
          include: paymentServiceDeepCheck
          show-details: always
        liveness:
          include: paymentServiceHealth
          show-details: always