# deployment/order-service.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: healthcheck-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: varunu2892/order-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8001
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: order-service-secret
                  key: ORDERDB_POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-service-secret
                  key: ORDERDB_POSTGRES_PASSWORD
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: order-service-secret
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-service-secret
                  key: RABBITMQ_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: healthcheck-demo
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  type: LoadBalancer