# deployment/payment-service.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: healthcheck-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: varunu2892/payment-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8002
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: paymentdb-postgres-secret
                  key: PAYMENTDB_POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: paymentdb-postgres-secret
                  key: PAYMENTDB_POSTGRES_PASSWORD
          readinessProbe:
            httpGet:
              port: 8002
              path: /actuator/health/paymentServiceDeepCheck
            initialDelaySeconds: 30 # Initial wait period
            periodSeconds: 10 # Interval between checks
          livenessProbe:
            httpGet:
              port: 8002
              path: /actuator/health/paymentServiceHealth
            initialDelaySeconds: 60
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: healthcheck-demo
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
  type: ClusterIP