services:
  postgres:
    container_name: payment-postgres
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=paymentdb'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
    ports:
      - '5432:5432'
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql